---
- name: My Playbook
  hosts: server1, server2 
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Upgrade packages
      apt:
        upgrade: safe
        autoremove: yes
      when: ansible_os_family == 'Debian'
 
